
language: go

sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

install:
  - go get github.com/boltdb/bolt
  - go get -u cloud.google.com/go/bigtable
  - go get github.com/google/badwolf/...
  - go get github.com/peterh/liner
  - go get github.com/pborman/uuid

script:
  - go test -v -race ./...
