
language: go

sudo: false

go:
  - "1.12"
  - "1.13"
  - tip

before_install:
  - go get github.com/boltdb/bolt
  - go get github.com/google/badwolf/...
  - go get github.com/peterh/liner
  - go get golang.org/x/net/context

script:
  - go test -v -race ./...
